global:
  scrape_interval: 15s
scrape_configs:
  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    kubernetes_sd_configs:
      - role: endpoints
        namespaces: {names: [traffic-platform]}
    relabel_configs:
      - {source_labels: [__meta_kubernetes_service_name], regex: gateway-service, action: keep}
      - {source_labels: [__meta_kubernetes_pod_name], target_label: pod}
  - job_name: feature-service
    metrics_path: /actuator/prometheus
    kubernetes_sd_configs:
      - role: endpoints
        namespaces: {names: [traffic-platform]}
    relabel_configs:
      - {source_labels: [__meta_kubernetes_service_name], regex: feature-service, action: keep}
      - {source_labels: [__meta_kubernetes_pod_name], target_label: pod}
  - job_name: decision-engine
    metrics_path: /actuator/prometheus
    kubernetes_sd_configs:
      - role: endpoints
        namespaces: {names: [traffic-platform]}
    relabel_configs:
      - {source_labels: [__meta_kubernetes_service_name], regex: decision-engine, action: keep}
      - {source_labels: [__meta_kubernetes_pod_name], target_label: pod}
  - job_name: ml-service
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
        namespaces: {names: [traffic-platform]}
    relabel_configs:
      - {source_labels: [__meta_kubernetes_service_name], regex: ml-service, action: keep}
      - {source_labels: [__meta_kubernetes_pod_name], target_label: pod}
